/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hikigaya
 */
public class databuku extends javax.swing.JFrame {

    /**
     * Creates new form databuku
     */
    public databuku() {
        initComponents();
        setkat();
    }
    
private void setkat(){
    cmbkat.addItem("Kategori");
    cmbkat.addItem("Novel");
    cmbkat.addItem("Pelajaran");
    cmbkat.addItem("Laporan");
    cmbkat.addItem("Tesis");
    
}

public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtjudul = new javax.swing.JTextField();
        txtpenerbit = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        cmbkat = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtjudul.setText("Judul");
        txtjudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtjudulMouseClicked(evt);
            }
        });

        txtpenerbit.setText("Penerbit");
        txtpenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpenerbitMouseClicked(evt);
            }
        });

        txtdesc.setText("isbn");
        txtdesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdescMouseClicked(evt);
            }
        });

        txtstok.setText("Stok");
        txtstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtstokMouseClicked(evt);
            }
        });
        txtstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstokKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstokKeyPressed(evt);
            }
        });

        txtpengarang.setText("Pengarang");
        txtpengarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpengarangMouseClicked(evt);
            }
        });

        cmbkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbkatMouseClicked(evt);
            }
        });

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbkat, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(submit))
                            .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbkat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
String kat = (String) cmbkat.getSelectedItem();
String jdl = (String) txtjudul.getText();
String penga = (String) txtpengarang.getText();
String pener = (String) txtpenerbit.getText();
String desc = (String) txtdesc.getText();
String stk = (String) txtstok.getText();


     if(kat.equals("Kategori")){
      JOptionPane.showMessageDialog(null, "Pilih Kategori!");
     }   
     else if(jdl.equals("")||penga.equals("")||pener.equals("")||desc.equals("")||stk.equals("")){
      JOptionPane.showMessageDialog(null, "Tidak Boleh Ada Yang Kosong!");     
     }
     else{
     try{
    String sql="select*from buku order by id_buku desc";
    Connection conn=(Connection) koneksi.koneksi();
   Statement stm = conn.createStatement();
    ResultSet res = stm.executeQuery(sql);
     String aidi;
    if(res.next()){
       
        String no=res.getString("id_buku").substring(1);
      String id = ""+(Integer.parseInt(no)+1);
      String nol=null;
      if(id.length()==1){
          nol="000";
      } 
      else if(id.length()==2){
          nol="00";
      }
       else if(id.length()==3){
          nol="0";
      }
       else if(id.length()==4){
          nol="";
      }
      aidi = "B"+nol+id; 
    }
    else{
       aidi = "B0001"; 
    }
    try {
            String query = "INSERT INTO buku VALUES "
                    + "('" + aidi+"','"+txtjudul.getText() + "','" + txtpengarang.getText() 
                    + "','" + txtpenerbit.getText() + "','" + cmbkat.getSelectedItem()  
                    + "','" + txtdesc.getText()+ "','" + txtstok.getText() + "')";
            java.sql.Connection kon = (Connection) koneksi.koneksi();
            java.sql.PreparedStatement mts = kon.prepareStatement(query);
            mts.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
   }  
catch(Exception b){
    JOptionPane.showMessageDialog(null,b.getMessage());
}
     new tabelbuku().setVisible(true);
dispose();
     }        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void txtjudulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjudulMouseClicked
txtjudul.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulMouseClicked

    private void txtpengarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpengarangMouseClicked
txtpengarang.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtpengarangMouseClicked

    private void txtpenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpenerbitMouseClicked
txtpenerbit.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenerbitMouseClicked

    private void txtdescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdescMouseClicked
txtdesc.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescMouseClicked

    private void cmbkatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbkatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkatMouseClicked

    private void txtstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtstokMouseClicked
txtstok.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokMouseClicked

    private void txtstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokKeyTyped
char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
                )
            )
        {
            evt.consume();
        }
 FilterAngka(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_txtstokKeyTyped

    private void txtstokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokKeyPressed

        
if (evt.getKeyCode()== KeyEvent.VK_ENTER){        
String kat = (String) cmbkat.getSelectedItem();
String jdl = (String) txtjudul.getText();
String penga = (String) txtpengarang.getText();
String pener = (String) txtpenerbit.getText();
String desc = (String) txtdesc.getText();
String stk = (String) txtstok.getText();


     if(kat.equals("Kategori")){
      JOptionPane.showMessageDialog(null, "Pilih Kategori!");
     }   
     else if(jdl.equals("")||penga.equals("")||pener.equals("")||desc.equals("")||stk.equals("")){
      JOptionPane.showMessageDialog(null, "Tidak Boleh Ada Yang Kosong!");     
     }
     else{
     try{
    String sql="select*from buku order by id_buku desc";
    java.sql.Connection conn=(Connection) koneksi.koneksi();
    java.sql.Statement stm = conn.createStatement();
    java.sql.ResultSet res = stm.executeQuery(sql);
     String aidi;
    if(res.next()){
       
        String no=res.getString("id_buku").substring(1);
      String id = ""+(Integer.parseInt(no)+1);
      String nol=null;
      if(id.length()==1){
          nol="000";
      } 
      else if(id.length()==2){
          nol="00";
      }
       else if(id.length()==3){
          nol="0";
      }
       else if(id.length()==4){
          nol="";
      }
      aidi = "B"+nol+id; 
    }
    else{
       aidi = "B0001"; 
    }
    try {
            String query = "INSERT INTO buku VALUES "
                    + "('" + aidi+"','"+txtjudul.getText() + "','" + txtpengarang.getText() 
                    + "','" + txtpenerbit.getText() + "','" + cmbkat.getSelectedItem()  
                    + "','" + txtdesc.getText()+ "','" + txtstok.getText() + "')";
            java.sql.Connection kon = (Connection) koneksi.koneksi();
            java.sql.PreparedStatement mts = kon.prepareStatement(query);
            mts.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
   }  
catch(Exception b){
    JOptionPane.showMessageDialog(null,b.getMessage());
}
     new databuku().setVisible(true);
dispose();
     }   
     
}// TODO add your handling code here:
    }//GEN-LAST:event_txtstokKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbkat;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
