/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;

import java.util.Calendar;
import java.util.GregorianCalendar;
import com.toedter.calendar.JCalendar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hikigaya
 */
public class Data_Peminjaman extends javax.swing.JFrame {
 private final Connection conn = koneksi.connect();
 private DefaultTableModel tabmode;    
public String kodebuku,namabuku,jumlah;
public String namapeminjam;
String pinjam;
String balik;


    /**
     * Creates new form Data_Peminjaman
     */
    public Data_Peminjaman() {
        initComponents();
        kalenderpeminjaman.setText("");
        tanggal();
       AutoNumber();
        txtkodepinjam.setEnabled(false);
        kalenderpeminjaman.setEnabled(false);
    }
    
    
protected void aktif() {
        
        tabmode=new DefaultTableModel();
        tabeldata.setModel(tabmode);
    }


 public void itempilihdatabuku(){
        pop_up_data_buku pilih =new pop_up_data_buku();
        pilih.abc=this;
        txtkodebuku.setText(kodebuku);
        txtnamabuku.setText(namabuku);
        txtstok.setText(jumlah);     
    }
 
public void itempilihpengunjung(){
pop_up_data_kelas pilih = new pop_up_data_kelas();
pilih.cba=this;

txtnamapeminjam.setText(namapeminjam);

} 


public void curentdate() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int year = cal.get(Calendar.YEAR);
        //kalenderpeminjaman.setText(year + "-" + (month + 1) + "-" + day);
    }
public void tanggal(){
Calendar cal = new GregorianCalendar();
int day = cal.get(Calendar.DAY_OF_MONTH);
int month =cal.get(Calendar.MONTH);
int year = cal.get(Calendar.YEAR);
kalenderpeminjaman.setText(day + "-" + (month + 1) + "-" + year);
}

   private void itung() {
        String a = txtstok.getText();
        String m = txtjumlahdipinjam.getText();

        if (txtjumlahdipinjam.getText() == null) {
            txtstok.setText(a);
        } else {
            int b = Integer.parseInt(a);
            int h = Integer.parseInt(m);
            int jumlah = b - h;
            String s = "" + jumlah;

            txtstok.setText(s);
        }
    }
 
    public void AutoNumber() {
        try {

             Connection conn = koneksi.connect();
      Statement stat = conn.createStatement();
            String query_bukaTabel = "select right(kode_peminjam,4) as no_urut from peminjaman";
           ResultSet line_result = stat.executeQuery(query_bukaTabel);
            if (line_result.first() == false) {
                txtkodepinjam.setText("P0001");
            } else {
                line_result.last();
                int no = line_result.getInt(1) + 1;
                String nomor = String.valueOf(no);
                int oto = nomor.length();
                
                for (int i = 0; i < 2 - oto; i++) {
                    nomor = "000" + nomor;
                }
                txtkodepinjam.setText("P" + nomor);
            }
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtkodepinjam = new javax.swing.JTextField();
        txtnamapeminjam = new javax.swing.JTextField();
        kalenderpengembalian = new com.toedter.calendar.JDateChooser();
        txtkodebuku = new javax.swing.JTextField();
        txtnamabuku = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        caripengunjung = new javax.swing.JButton();
        caridatabuku = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtjumlahdipinjam = new javax.swing.JTextField();
        kalenderpeminjaman = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        boxstatus = new javax.swing.JComboBox<>();
        tes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 700));
        setPreferredSize(new java.awt.Dimension(1270, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtkodepinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 250, 33));
        getContentPane().add(txtnamapeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 250, 33));
        getContentPane().add(kalenderpengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 250, 33));
        getContentPane().add(txtkodebuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 250, 33));
        getContentPane().add(txtnamabuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 250, 33));

        jLabel1.setText("Tanggal Pengembalian");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 170, 30));

        jLabel4.setText("Nama Pengunjung");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 30));

        jLabel5.setText("Tanggal Peminjaman");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 160, 30));

        jLabel6.setText("Nama Buku");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 30));

        jLabel7.setText("Jumlah Buku");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 150, 30));

        jLabel8.setText("Kode Buku");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 30));

        caripengunjung.setText("Cari");
        caripengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caripengunjungActionPerformed(evt);
            }
        });
        getContentPane().add(caripengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 70, -1));

        caridatabuku.setText("cari");
        caridatabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridatabukuActionPerformed(evt);
            }
        });
        getContentPane().add(caridatabuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 70, -1));

        jLabel2.setText("Kode_peminjam");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 30));

        txtjumlahdipinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahdipinjamKeyReleased(evt);
            }
        });
        getContentPane().add(txtjumlahdipinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 80, 33));
        getContentPane().add(kalenderpeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 250, 33));
        getContentPane().add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 90, 33));

        jLabel9.setText("Stok");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 40, 30));

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 103, 600, 270));

        boxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Di kembalikan" }));
        getContentPane().add(boxstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 260, 30));

        tes.setText("Simpan");
        tes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesActionPerformed(evt);
            }
        });
        getContentPane().add(tes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caridatabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridatabukuActionPerformed
        // TODO add your handling code here:
         pop_up_data_buku Pp=new pop_up_data_buku();
        Pp.abc=this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_caridatabukuActionPerformed

    private void caripengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caripengunjungActionPerformed
   pop_up_data_kelas a =new pop_up_data_kelas();
   a.cba=this;
  a.setVisible(true);
  a.setResizable(false);
 // TODO add your handling code here:
    }//GEN-LAST:event_caripengunjungActionPerformed

    private void txtjumlahdipinjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahdipinjamKeyReleased
    itung();        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahdipinjamKeyReleased

    private void tesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesActionPerformed
 if(kalenderpeminjaman.getText().equals("")&&kalenderpengembalian.getDate().equals("")){
   JOptionPane.showMessageDialog(null,"Tidak Boleh Ada yang kosong");  
 }
 else{
        try{
     String aidi1;
      aidi1=txtkodebuku.getText();
            String query = "select*from data_buku where kode = '"+aidi1+"'";
            java.sql.Connection kon = (Connection) koneksi.connect();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);
            
            while(data.next()){
            String jmlh = txtjumlahdipinjam.getText();
            String stk = data.getString(8);
           int stok = Integer.parseInt(stk);
           int jumlah = Integer.parseInt(jmlh);
           if(stok == 0){
              JOptionPane.showMessageDialog(null,"Stok Buku Telah Kosong!"); 
           }
           else if(jumlah>stok){
             JOptionPane.showMessageDialog(null,"Jumlah Buku Tidak Cukup!"); 
           }
           else{
               
    try{
    String sql1="select*from peminjaman order by kode_peminjam desc";
    java.sql.Connection conn=(Connection) koneksi.connect();
    java.sql.Statement stm1 = conn.createStatement();
    java.sql.ResultSet res1 = stm1.executeQuery(sql1);
     String aidi;
    if(res1.next()){
       
        String no=res1.getString("kode_peminjam").substring(1);
      String id = ""+(Integer.parseInt(no)+1);
      String nol=null;
      if(id.length()==1){
          nol="000";
      } 
      else if(id.length()==2){
          nol="00";
      }
       else if(id.length()==3){
          nol="0";
      }
       else if(id.length()==4){
          nol="";
      }
      aidi = "P"+nol+id; 
    }
    else{
       aidi = "P0001"; 
    }
    try {
         
     int denda=0;
            String query1 = "INSERT INTO peminjaman VALUES "
                    + "('" + aidi+"','"
                    +txtnamapeminjam.getText()
                    + "','" + txtkodebuku.getText() 
                    + "','" + txtnamabuku.getText() 
                    + "','" + txtjumlahdipinjam.getText()  
            
                    + "','" + pinjam
                    + "','" + balik
                   
                    + "','" + boxstatus.getSelectedItem().toString()+ "')";
            java.sql.Connection kon1 = (Connection) koneksi.connect();
            java.sql.PreparedStatement mts = kon1.prepareStatement(query1);
            mts.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            
         try{
  String query2 = "select*from data_buku where kode = '"+txtkodebuku.getText()+"'";
 java.sql.Connection kon2 = (Connection) koneksi.connect();
 java.sql.Statement st = kon2.createStatement();
 java.sql.ResultSet data2 = st.executeQuery(query2);
 
 while(data2.next()){
     int jumlah1= Integer.parseInt(data2.getString(8));
     int jumlahpinjam = Integer.parseInt(txtjumlahdipinjam.getText());
     int total = jumlah1-jumlahpinjam;
    try {
            String sql3 ="UPDATE data_buku SET jumlah = '"+total
                    +"' WHERE kode = '"+txtkodebuku.getText()+"'";
            java.sql.Connection conn1=(Connection)koneksi.connect();
            java.sql.PreparedStatement pst=conn1.prepareStatement(sql3);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
    
        }
        }
          catch(Exception b){
            JOptionPane.showMessageDialog(null, b.getMessage());
        }

new datapinjam().setVisible(true);
dispose();
 AutoNumber();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
        }   
        catch(Exception b){
         JOptionPane.showMessageDialog(null,b.getMessage());
        }            
        
        }
        
        }
            
        }
        catch(Exception b){
         JOptionPane.showMessageDialog(null,b.getMessage());    
        }
     
      }          // TODO add your handling code here:
    }//GEN-LAST:event_tesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxstatus;
    private javax.swing.JButton caridatabuku;
    private javax.swing.JButton caripengunjung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kalenderpeminjaman;
    private com.toedter.calendar.JDateChooser kalenderpengembalian;
    private javax.swing.JTable tabeldata;
    private javax.swing.JButton tes;
    private javax.swing.JTextField txtjumlahdipinjam;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtkodepinjam;
    private javax.swing.JTextField txtnamabuku;
    private javax.swing.JTextField txtnamapeminjam;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
