/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;

import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hikigaya
 */
public class Pengembalian extends javax.swing.JFrame {
String kembali;
String pulang;
    private final Connection conn = koneksi.connect();

    /**
     * Creates new form Pengembalian
     */
    public Pengembalian() {
        initComponents();
        tampil();
    }
    
private void kosong(){
    txttelat.setEditable(true);
    txtdenda.setEditable(true);
    txtbayar.setEditable(true);
    txtkembalian.setEditable(true);
    tglkembali.setDate(null);
    tglkembali.setEnabled(false);  
    
    txtid.setText("ID Peminjaman");
    txtpinjam.setText("Tanggal Peminjaman");
    txtblk.setText("Tanggal Balik");
    txttelat.setText("Keterlambatan");
    txtdenda.setText("Denda");
    txtbayar.setText("Bayar");
    txtkembalian.setText("Kembali"); 
    txtkembalian.setEditable(false);
       txtid.setEditable(false);
       txtpinjam.setEditable(false);
       txtblk.setEditable(false);
       txttelat.setEditable(false);
       txtdenda.setEditable(false);
    tglkembali.setEnabled(false);
    btnhitung.setEnabled(false);
  btnbatal.setEnabled(false);
  btnproses.setEnabled(false);
  
       
}     
    
private void tampil(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nama");
        model.addColumn("Kode Buku");
        model.addColumn("Nama Buku");
        model.addColumn("Jumlah");
        model.addColumn("Tanggal Pinjaman");
        model.addColumn("Tanggal Pengembalian");
        model.addColumn("Denda");
        model.addColumn("Status");
        
        try{
            String status = "Belum Di kembalikan";
            String query = "select*from peminjaman where status = '"+status+"'";
            java.sql.Connection kon = (Connection) koneksi.connect();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);
            
            while(data.next()){
                model.addRow(new Object [] {
                data.getString(1),
                data.getString(2),
                data.getString(3),
                data.getString(4),
                data.getString(5),
                data.getString(6),
                data.getString(7),
                data.getString(8),
                data.getString(9)
                });
            }
            tblpinjam.setModel(model);
        }
        catch(Exception b){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblpinjam = new javax.swing.JTable();
        txtid = new javax.swing.JTextField();
        txtpinjam = new javax.swing.JTextField();
        txtblk = new javax.swing.JTextField();
        tglkembali = new com.toedter.calendar.JDateChooser();
        txtkembalian = new javax.swing.JTextField();
        txttelat = new javax.swing.JTextField();
        txtdenda = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        btnproses = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1270, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblpinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpinjam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 50, 1135, 250));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 223, 45));
        getContentPane().add(txtpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 223, 42));
        getContentPane().add(txtblk, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 223, 47));

        tglkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglkembaliPropertyChange(evt);
            }
        });
        getContentPane().add(tglkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 215, 40));
        getContentPane().add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 230, 40));
        getContentPane().add(txttelat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 230, 40));
        getContentPane().add(txtdenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 230, 40));

        txtbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbayarMouseClicked(evt);
            }
        });
        getContentPane().add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 230, 40));

        btnhitung.setText("hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, -1, -1));

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });
        getContentPane().add(btnproses, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        btnbatal.setText("batal");
        getContentPane().add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblpinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpinjamMouseClicked
        // TODO add your handling code here:
        btnbatal.setEnabled(true);   
tglkembali.setEnabled(true);
txtbayar.setEditable(true);
        try{
        
     int baris = tblpinjam.getSelectedRow();
        String id= tblpinjam.getValueAt(baris, 0).toString();
        
            String query = "select*from peminjaman where kode_peminjam = '"+id+"'";
            java.sql.Connection kon = (Connection) koneksi.connect();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);
            
            while(data.next()){
        
                txtid.setText(data.getString(1));
            txtpinjam.setText(data.getString(6));
            txtblk.setText(data.getString(7));
            kembali = data.getString(7);
            }
            
    }
        catch(Exception b){
            
        }
    }//GEN-LAST:event_tblpinjamMouseClicked

    private void tglkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglkembaliPropertyChange
if (tglkembali.getDate() != null) {
     SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd-MM-yyyy");
     pulang = FormatTanggal.format(tglkembali.getDate());
}
try {
    DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    Date tanggalpinjam = format.parse(kembali);
    Date tanggalkembali = format.parse(pulang);
    long tanggalpinjam1 = tanggalpinjam.getTime();
    long tanggalkembali1 = tanggalkembali.getTime();
    long diff = tanggalkembali1 - tanggalpinjam1;
    long lama = diff / (24 * 60 * 60 * 1000);
    txttelat.setText(Long.toString(lama) + "");

int denda;
int telat = Integer.parseInt(txttelat.getText());
denda = telat*1000;
String tlt;
 tlt = String.valueOf(denda);   
if(telat<0){
txttelat.setText("Keterlambatan");
txtdenda.setText("Denda");
txtbayar.setText("Bayar");
txtkembalian.setText("Kembali");
btnhitung.setEnabled(false);  
btnproses.setEnabled(false);
btnbatal.setEnabled(true);
}
else if(tlt.equals("0")){
txtbayar.setText("0");
 txtdenda.setText("0");
txtkembalian.setText("0");
txtbayar.setEditable(false);
btnhitung.setEnabled(false);
btnproses.setEnabled(true);
btnbatal.setEnabled(true);
}
else{
txtbayar.setEditable(true);
txtbayar.setText("Bayar");
txtkembalian.setText("Kembali");
btnhitung.setEnabled(true); 
btnproses.setEnabled(true);
btnbatal.setEnabled(true);
txtdenda.setText(tlt);
}
} catch (Exception e) {
    System.out.println("" + e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkembaliPropertyChange

    private void txtbayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbayarMouseClicked
txtbayar.setText(null);            // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarMouseClicked

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
int bayar = Integer.parseInt(txtbayar.getText());
int denda = Integer.parseInt(txtdenda.getText());

if(bayar<denda){
   JOptionPane.showMessageDialog(null,"Tidak Boleh Kurang!"); 
}
else{
  int total = bayar-denda;
String ttl;
ttl = String.valueOf(total);
txtkembalian.setText(ttl);
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
try {
        String status = "Sudah Kembali";
            String sql ="UPDATE peminjaman SET denda = '"+txtdenda.getText()
                    +"',status = '"+status
                    +"' WHERE kode_peminjam = '"+txtid.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.connect();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
 try{
        
        String id= txtid.getText();
        
            String query = "select kode_buku from peminjaman where kode_peminjam = '"+id+"'";
            java.sql.Connection kon = (Connection) koneksi.connect();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);
            
            while(data.next()){
        String aidi = data.getString("kode_buku");
        try{
  String query1 = "select*from data_buku where kode = '"+aidi+"'";
 java.sql.Connection kon1 = (Connection) koneksi.connect();
 java.sql.Statement st = kon1.createStatement();
 java.sql.ResultSet data1 = st.executeQuery(query1);
 
 while(data1.next()){
      int baris = tblpinjam.getSelectedRow();
        String jmlh= tblpinjam.getValueAt(baris, 5).toString();
     int jumlah= Integer.parseInt(data1.getString(6));
     int jumlahpinjam = Integer.parseInt(jmlh);
     int total = jumlah+jumlahpinjam;
    try {
            String sql1 ="UPDATE data_buku SET jumlah = '"+total
                    +"' WHERE kode = '"+aidi+"'";
            java.sql.Connection conn1=(Connection)koneksi.connect();
            java.sql.PreparedStatement pst=conn1.prepareStatement(sql1);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
     
 }
}
catch(Exception b){
 JOptionPane.showMessageDialog(null, b.getMessage());
}
            }
            
    }
        catch(Exception b){
            
        }
 tampil();
 kosong();        // TODO add your handling code here:
    }//GEN-LAST:event_btnprosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnproses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpinjam;
    private com.toedter.calendar.JDateChooser tglkembali;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtblk;
    private javax.swing.JTextField txtdenda;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtpinjam;
    private javax.swing.JTextField txttelat;
    // End of variables declaration//GEN-END:variables
}
